name: Coana Vulnerability Analysis

on:
  schedule:
    - cron: '0 3 * * *' # every day at 3 AM
  workflow_dispatch: # run manually

jobs:
  coana-vulnerability-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Coana CLI
        id: coana-cli
        uses: docker://coana/coana:latest
        with: 
          args: |
            coana run . \
              --api-key ${{ secrets.COANA_API_KEY_PUBLIC_REPOS }} \
              --repo-url https://github.com/${{github.repository}}